[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "scipy",
    "numpy",
    "matplotlib",
]
name = "lyaponov"
version = "0.1.1"